export const UPDATE_FIELD = "UPDATE_FIELD";
export const UPDATE_ERROR_MESSAGES = "UPDATE_ERROR_MESSAGES";
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
